### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by dark159123** [zayronxio/Zafiro-icons#6]
# Wine apps:
![screenshot-20180422101726](https://user-images.githubusercontent.com/18619090/39092926-4b549786-4617-11e8-8076-36566d8567fe.png)
![screenshot-20180422101735](https://user-images.githubusercontent.com/18619090/39092927-4b6eac20-4617-11e8-98dc-c944080b8245.png)
![screenshot-20180422101833](https://user-images.githubusercontent.com/18619090/39092928-4b8da440-4617-11e8-9d80-0d6779951d2c.png)
![screenshot-20180422101840](https://user-images.githubusercontent.com/18619090/39092929-4ba620ce-4617-11e8-84cb-0917b63eddaf.png)
![screenshot-20180422101847](https://user-images.githubusercontent.com/18619090/39092930-4bcf39dc-4617-11e8-9f1b-4a9f36c52d29.png)
![screenshot-20180422101852](https://user-images.githubusercontent.com/18619090/39092931-4bfb7f4c-4617-11e8-8b83-ff71507da101.png)

# Some open source games
![screenshot-20180422101524](https://user-images.githubusercontent.com/18619090/39092939-8abfccb0-4617-11e8-9a7b-9905ab15d3d2.png)
![screenshot-20180422101645](https://user-images.githubusercontent.com/18619090/39092940-8adb6eac-4617-11e8-9202-41d0066c023d.png)
![screenshot-20180422101713](https://user-images.githubusercontent.com/18619090/39092941-8af38320-4617-11e8-91d8-0cc279deed88.png)
![screenshot-20180422101810](https://user-images.githubusercontent.com/18619090/39092942-8b0c35a0-4617-11e8-95b1-e5f934868965.png)
![screenshot-20180422101801](https://user-images.githubusercontent.com/18619090/39092968-e9c6e7f2-4617-11e8-9b82-b8023281fc53.png)

# Unsorted icons
![screenshot-20180422101500](https://user-images.githubusercontent.com/18619090/39092946-b991642c-4617-11e8-9417-32e4690336fe.png)
![screenshot-20180422101510](https://user-images.githubusercontent.com/18619090/39092947-b9ac31ee-4617-11e8-9889-98de1dbdb221.png)
![screenshot-20180422101518](https://user-images.githubusercontent.com/18619090/39092948-b9c4f1fc-4617-11e8-91d5-49fe6ba15624.png)
![screenshot-20180422101544](https://user-images.githubusercontent.com/18619090/39092949-b9dc3dda-4617-11e8-8344-f0e030ea96b5.png)
![screenshot-20180422101609](https://user-images.githubusercontent.com/18619090/39092950-ba105be2-4617-11e8-88ad-e21af54b0e0a.png)
![screenshot-20180422101651](https://user-images.githubusercontent.com/18619090/39092951-ba2b5000-4617-11e8-9b42-5264719439f8.png)
![screenshot-20180422101657](https://user-images.githubusercontent.com/18619090/39092952-ba452ec6-4617-11e8-9286-d6985776c3eb.png)
![screenshot-20180422101705](https://user-images.githubusercontent.com/18619090/39092953-ba5f1692-4617-11e8-925b-ce662d290689.png)
![screenshot-20180422101751](https://user-images.githubusercontent.com/18619090/39092954-ba782056-4617-11e8-816b-bbef4e23bc58.png)
![screenshot-20180422101756](https://user-images.githubusercontent.com/18619090/39092969-f17db6e2-4617-11e8-81d4-ad2548903d7f.png)

**Comment by zayronxio** [comment]
Thanks for reporting, they will be added as soon as possible

**Comment by masaxo00** [comment]
Hi!, i found that the LMMS icon is missing.

![icon](https://user-images.githubusercontent.com/29778990/39666414-ba3be70a-5079-11e8-92c6-4a3cfec192a2.png)

Thanks for doing this!

**Comment by zayronxio** [comment]
dark159123

atom is already added, however if you are using the snap package, it is unlikely that the icon will change, it is a problem with the snap packages

**Comment by wsdfhjxc** [comment]
Hello.

It will be great if you can adapt the KDevelop icon for Zafiro.

Here's how the original one looks like:
![kdevelop](https://user-images.githubusercontent.com/20323160/40925296-b26fa0fe-6819-11e8-8ff1-5eec145705b9.png)

Thanks in advance!

**Comment by OctoPenguin** [comment]
VLC icon is mssing.

**Comment by mhsabbagh** [comment]
Thunar navigation icons are too big, are they missing so another icons are being used in place..?

![screenshot from 2018-10-01 14-26-55](https://user-images.githubusercontent.com/1293003/46285996-23b2a580-c586-11e8-844e-9db06f1ebc62.png)

**Comment by zayronxio** [comment]
hi mate, periodically I install different dekstops to polish the experience in each one, the last ones have been deepin and kde respectively, this week I will be using xubuntu, with xfce of course, then these errors that you mention will be solved this week,

**Comment by mhsabbagh** [comment]
That's nice to hear! I really like your icons. Keep up the good work!

**Comment by WingofaGriffin** [comment]
Hey! Love the icons! Wanted to show off a couple of edge cases I found.

Arch Cinnamon:
Blueman and Redshift in the task bar don't seem to work 
![image](https://user-images.githubusercontent.com/19497824/46896011-04026380-ce49-11e8-8d81-e7a9a03ed0f9.png)

Joplin and OBS and Xournal are missing. My Geary fork doens't use the standard Geary icon you have. Is it possible to just * notation to do a catch all?
![image](https://user-images.githubusercontent.com/19497824/46896182-da960780-ce49-11e8-8a42-accebee7c071.png)

System Settings is missing a lot (not all are shown)
![image](https://user-images.githubusercontent.com/19497824/46896162-c81bce00-ce49-11e8-92c5-b5c9f1238bc9.png)

Keep up the good work! I love everything I've seen so far :)

**Comment by APakrohk** [comment]
Perspolise DM 
https://persepolisdm.github.io/
RamBox 
https://rambox.pro/#home
itch Game Store
https://itch.io
OpenSpades
https://github.com/yvt/openspades
############################################################
plz add :1st_place_medal:  :+1:

**Comment by zayronxio** [comment]
Gimli144 icons added

**Comment by zayronxio** [comment]
@APakrohk I have added some of the icons that you mention, I hope to complete your order soon

**Comment by zayronxio** [comment]
@WingofaGriffin I have added some of the icons that you mention, I hope to complete your order soon

**Comment by Gimli144** [comment]
Hi,
found some missing icons:
Dosbox emulator
![image](https://user-images.githubusercontent.com/42769210/47956830-5c8dd200-dfab-11e8-8961-9d5fcacd30d4.png)
![image](https://user-images.githubusercontent.com/42769210/47956838-8515cc00-dfab-11e8-949b-82c553d8187d.png)
![image](https://user-images.githubusercontent.com/42769210/47956843-9f4faa00-dfab-11e8-8c4c-762201971230.png)
![image](https://user-images.githubusercontent.com/42769210/47956846-b8f0f180-dfab-11e8-8a3e-6e7e8bbf14ab.png)
![image](https://user-images.githubusercontent.com/42769210/47956848-cd34ee80-dfab-11e8-8864-b32ce3e8f4b1.png)
![image](https://user-images.githubusercontent.com/42769210/47956851-e0e05500-dfab-11e8-9ca1-8c4df16df9f2.png)

**Comment by zayronxio** [comment]
@mhsabbagh I have slightly changed the size of the navigation icons, I have also added some icons for the notification tray in the panel, I hope that both problems are solved, I hope your answer

**Comment by zayronxio** [comment]
@Gimli144 the icon of dosbox is for some time, as well as the one of spotify, it is probable that you are using snad packages in ubuntu, these packages do not allow to modify the icons

**Comment by mhsabbagh** [comment]
The navigation icons of Thunar are still big, also the system tray icon for the power manager is still the same:

![screenshot from 2018-11-12 08-03-23](https://user-images.githubusercontent.com/1293003/48327819-da0fad00-e651-11e8-9f2a-52fa92911e6b.png)


Compare this to the size of the navigation icons in Papirus for example:

![screenshot from 2018-11-12 08-06-52](https://user-images.githubusercontent.com/1293003/48327827-ef84d700-e651-11e8-8391-8c1a2877eea7.png)

**Comment by WingofaGriffin** [comment]
Blueman is now broken in cinnamon
![image](https://user-images.githubusercontent.com/19497824/48567892-3120b680-e8cc-11e8-99ea-78d3901901d7.png)

Also missing Lutris, Flameshot, and OnlyOffice

**Comment by zayronxio** [comment]
@Gimli144 
fprint-demo has been added, in what refers to dosbox, the icon already exists, it is problems that you are using a snap package, if it is the case, then you can not see the icons

**Comment by Gimli144** [comment]
The fprint-demo icon didn't work out of the box, I had to rename the symlink from "fprint-demo.svg" to "fprint_demo.svg" with underscore.

The Desktop entry:
    [Desktop Entry]
    Name=fprint-demo
    GenericName=Fingerprint demo program
    GenericName[fr]=Logiciel de démonstration de reconnaissances des empreintes digitales
    Comment=Fingerprint scanning demonstration
    Comment[ca]=Programari de demostració de reconeixement d'emprentes digitals
    Comment[es]=Programa de demostración de reconocimiento de huellas digitales
    Comment[fr]=Logiciel de démonstration pour le programme de reconnaissance d'empreinte digitale fprint
    Exec=fprint_demo
    Icon=fprint_demo
    Terminal=false
    Type=Application
    Categories=Utility;ComputerScience;ImageProcessing;
